AllCops:
  TargetRubyVersion: 2.0

LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Exclude:
    - "**/*_test.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_test.rb"